# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNtZDbGgg8cLoXP81Vzu7vGFf-9dKSOc
"""

import requests
import pandas as pd
import re

html = requests.get('https://www.alta.ru/currency/').text

tables = tables = pd.read_html(html)[7] # [6] - основные валюты
tables.columns = ['key', 'currency', 'rate']  
tables

table_key = tables['key'].str.split(' ',expand=True)
table_key.columns=['number_key','name_key']
table_key

tables = (pd.concat([table_key,tables],axis=1)).drop('key',axis=1)
tables

table_course = pd.concat([tables['currency'], tables['rate']],axis=1)
table_course

table_currency = table_course['currency']
#multiplier = table_course['currency'][0].find('(за ')
table_currency = table_currency.str.split('  ',expand=True)
table_currency.columns=['name_currency','multiplier']
for n in range(115):
   table_currency['multiplier'][n] = int(''.join(re.findall('\d+', table_currency['multiplier'][n])))
table_currency

table_course = (pd.concat([table_currency,table_course],axis=1)).drop('currency',axis=1)

for n in range(115):
  table_course['rate'][n] /=  table_course['multiplier'][n]

table_course = table_course.drop('multiplier',axis=1)

df = pd.concat([table_key,table_course],axis=1)
df